version: "3.9"

services:
  web:
    build: .
    container_name: data_science_agent
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
      - /app/.venv # masks the .venv folder so host venv is ignored
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
